name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123412341234123
    runs-on: ubuntu-latest

    steps:
      - name: "Display Message"
        run: echo "hello mundo"

      - name: "Display env var"
        if: ${{ env.platform == 'azure'}}
        run: |
          echo "Platform option: ${{ env.platform }}"
          echo "Region option: ${{ env.region }}"
          echo "Account option: ${{ env.account }}"
